
// Part of the ProceduralTextureMaker project.
// http://github.com/johanokl/ProceduralTextureMaker
// Released under GPLv3.
// Johan Lindqvist (johan.lindqvist@gmail.com)

#ifndef TEXTURERENDERTHREAD_H
#define TEXTURERENDERTHREAD_H

#include "texturenode.h"
#include <atomic>
#include <QSize>
class TextureProject;

/// @brief Renders texture images on a dedicated worker thread.
/// @details Each instance handles one image size and remains idle when no image requires rendering.
class TextureRenderThread : public QObject {
   Q_OBJECT

public:
   /// @brief Constructs a renderer for a fixed image size.
   /// @param renderSize The dimensions of the images generated by this renderer.
   /// @param nodes An initial snapshot of the project nodes.
   TextureRenderThread(const QSize renderSize, QMap<int, TextureNodePtr> nodes);
   ~TextureRenderThread() override = default;

   /// @brief Requests rendering to stop after the current image finishes rendering.
   void abort();

public slots:
   /// @brief Regenerates invalidated images after a node update.
   void imageUpdated();

   /// @brief Removes a node from this renderer's local node map.
   /// @param remNode The ID of the node to remove.
   void nodeRemoved(int remNode);

   /// @brief Adds a node to this renderer's local node map and renders its image if necessary.
   /// @param newNode The node to add.
   void nodeAdded(const TextureNodePtr& newNode);

private:
   /// @brief Generates missing images until all render-ready nodes are processed or rendering
   /// stops.
   void generate();
   const QSize renderSize;
   QMap<int, TextureNodePtr> nodes;
   std::atomic_bool aborted;
};

#endif  // TEXTURERENDERTHREAD_H
